/-
LTFP §9.2 — Single hidden-layer neural networks.

Bach (2024) §9.2, pp. 249-256. A single-hidden-layer NN is
`f(x) = ∑ⱼ aⱼ · σ(wⱼᵀ x + bⱼ)` where `σ` is the activation function
(typically ReLU), `wⱼ ∈ ℝᵈ` are hidden-layer weights, `bⱼ ∈ ℝ` biases,
and `aⱼ ∈ ℝ` output weights.
-/
import LTFP.Foundations.NeuralNet
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Data.Fintype.BigOperators

namespace LTFP

variable {d : ℕ} {m : ℕ}  -- d = input dim, m = hidden width

/-- §9.2 — Single hidden-layer ReLU network with `m` neurons. -/
noncomputable def singleHiddenReLU
    (w : Fin m → Fin d → ℝ) (b : Fin m → ℝ) (a : Fin m → ℝ)
    (x : Fin d → ℝ) : ℝ :=
  ∑ j, a j * relu (∑ i, w j i * x i + b j)

/-- §9.2 sanity lemma: a width-zero network outputs zero. -/
theorem singleHiddenReLU_zero_width
    (w : Fin 0 → Fin d → ℝ) (b : Fin 0 → ℝ) (a : Fin 0 → ℝ)
    (x : Fin d → ℝ) :
    singleHiddenReLU w b a x = 0 := by
  unfold singleHiddenReLU
  simp

/-- §9.2 sanity lemma: zero output weights produce the zero function. -/
theorem singleHiddenReLU_zero_output
    (w : Fin m → Fin d → ℝ) (b : Fin m → ℝ) (x : Fin d → ℝ) :
    singleHiddenReLU w b (fun _ => 0) x = 0 := by
  unfold singleHiddenReLU
  simp

/-- §9.3 — Linearity of the network output in the output weights `a`:
    `f_{a₁ + a₂}(x) = f_{a₁}(x) + f_{a₂}(x)`.  This is the algebraic
    core of the additive variation-norm framework on p. 257-260. -/
theorem singleHiddenReLU_add_a
    (w : Fin m → Fin d → ℝ) (b : Fin m → ℝ) (a1 a2 : Fin m → ℝ)
    (x : Fin d → ℝ) :
    singleHiddenReLU w b (a1 + a2) x =
      singleHiddenReLU w b a1 x + singleHiddenReLU w b a2 x := by
  simp only [singleHiddenReLU, Pi.add_apply, add_mul,
             Finset.sum_add_distrib]

/-- §9.2 — Zero-bias single-neuron sanity: just relu of a linear form. -/
theorem singleHiddenReLU_with_zero_bias_one_neuron
    (w : Fin 1 → Fin d → ℝ) (a : Fin 1 → ℝ) (x : Fin d → ℝ) :
    singleHiddenReLU w (fun _ => 0) a x =
      a 0 * relu (∑ i, w 0 i * x i) := by
  unfold singleHiddenReLU
  simp

/-- §9.2 — Network with zero input vector: only the bias terms contribute. -/
theorem singleHiddenReLU_zero_input
    (w : Fin m → Fin d → ℝ) (b : Fin m → ℝ) (a : Fin m → ℝ) :
    singleHiddenReLU w b a (fun _ => 0) =
      ∑ j, a j * relu (b j) := by
  simp [singleHiddenReLU]

/-- §9.3 — Network output is nonneg-additive in the output weights. -/
theorem singleHiddenReLU_zero_a (w : Fin m → Fin d → ℝ) (b : Fin m → ℝ)
    (x : Fin d → ℝ) :
    singleHiddenReLU w b (0 : Fin m → ℝ) x = 0 := by
  unfold singleHiddenReLU
  simp

/-! ## §9.2 — Ramp function: the building block of universal approximation

The Cybenko/Hornik universal approximation theorem (Bach 2024 §9.2,
pp. 249-256) states that single-hidden-layer networks with continuous
sigmoidal/ReLU activation are dense in `C([0,1]ⁿ)` w.r.t. the sup norm.
The full density-in-`C(K)` proof requires Stone-Weierstrass on the
algebra generated by ridge functions plus Hahn-Banach separation; this
glue is a Mathlib gap (see `PROGRESS.md`, Tier C ledger).

What we *can* prove honestly here is the **algebraic building block**:
the difference of two ReLU activations evaluated at shifted inputs is
the canonical *ramp* — a continuous piecewise-linear function bounded
between 0 and 1, equal to 0 below `t`, equal to 1 above `t + 1`, and
linear in between. Linear combinations of ramps form an `m`-dense
subalgebra of `C([a,b])` and underwrite the UAT for `n = 1`.

The ramp is `ramp t x := relu (x - t) - relu (x - t - 1)`. -/

/-- §9.2 — The ramp function, a difference of two ReLUs. -/
noncomputable def ramp (t x : ℝ) : ℝ := relu (x - t) - relu (x - t - 1)

/-- §9.2 — The ramp is bounded below by 0. -/
theorem ramp_nonneg (t x : ℝ) : 0 ≤ ramp t x := by
  unfold ramp relu
  -- Show `max (x - t - 1) 0 ≤ max (x - t) 0`.
  have h : max (x - t - 1) 0 ≤ max (x - t) 0 :=
    max_le_max (by linarith) le_rfl
  linarith

/-- §9.2 — The ramp is bounded above by 1. -/
theorem ramp_le_one (t x : ℝ) : ramp t x ≤ 1 := by
  unfold ramp relu
  -- Case split on the sign of `x - t - 1`.
  by_cases h : 0 ≤ x - t - 1
  · -- Then `x - t ≥ 1 > 0`, and both maxes drop their zero branch.
    have hxt : 0 ≤ x - t := by linarith
    rw [max_eq_left hxt, max_eq_left h]
    linarith
  · push_neg at h
    -- Here `max (x - t - 1) 0 = 0`, so the difference is just `max (x - t) 0`.
    rw [max_eq_right (le_of_lt h)]
    -- Need `max (x - t) 0 - 0 ≤ 1`, i.e. `max (x - t) 0 ≤ 1`.
    by_cases h2 : 0 ≤ x - t
    · rw [max_eq_left h2]; linarith
    · push_neg at h2
      rw [max_eq_right (le_of_lt h2)]; linarith

/-- §9.2 — The ramp is bounded in `[0, 1]`. -/
theorem ramp_in_unit_interval (t x : ℝ) : 0 ≤ ramp t x ∧ ramp t x ≤ 1 :=
  ⟨ramp_nonneg t x, ramp_le_one t x⟩

/-- §9.2 — Ramp value below `t` (the "−∞ limit" / left flat region):
when `x ≤ t`, both ReLUs vanish and the ramp equals 0. -/
theorem ramp_eq_zero_of_le (t x : ℝ) (hx : x ≤ t) : ramp t x = 0 := by
  unfold ramp
  have h1 : x - t ≤ 0 := by linarith
  have h2 : x - t - 1 ≤ 0 := by linarith
  rw [relu_of_nonpos _ h1, relu_of_nonpos _ h2, sub_zero]

/-- §9.2 — Ramp value above `t + 1` (the "+∞ limit" / right flat region):
when `x ≥ t + 1`, the ramp telescopes to `1`. -/
theorem ramp_eq_one_of_ge (t x : ℝ) (hx : t + 1 ≤ x) : ramp t x = 1 := by
  unfold ramp
  have h1 : 0 ≤ x - t := by linarith
  have h2 : 0 ≤ x - t - 1 := by linarith
  rw [relu_of_nonneg _ h1, relu_of_nonneg _ h2]
  linarith

/-- §9.2 — In the linear region `t ≤ x ≤ t + 1`, the ramp equals `x - t`. -/
theorem ramp_eq_linear_of_mem (t x : ℝ) (hx1 : t ≤ x) (hx2 : x ≤ t + 1) :
    ramp t x = x - t := by
  unfold ramp
  have h1 : 0 ≤ x - t := by linarith
  have h2 : x - t - 1 ≤ 0 := by linarith
  rw [relu_of_nonneg _ h1, relu_of_nonpos _ h2, sub_zero]

end LTFP
