/-
Umbrella file for the `LTFP.MathlibExt` namespace.

This collects Mathlib-quality extension modules developed inside LTFP-Lean
that are candidates for an upstream pull request.  Each module follows
Mathlib coding conventions (full docstrings, namespaced declarations,
no `sorry`).
-/

import LTFP.MathlibExt.Analysis.Smoothness
import LTFP.MathlibExt.Analysis.Subgradient.L1
import LTFP.MathlibExt.Analysis.Subgradient.SumRule
import LTFP.MathlibExt.Analysis.InnerProductSpace.RKHS
import LTFP.MathlibExt.Calculus.FDerivInnerGradient
import LTFP.MathlibExt.Calculus.FunctionMovementAlongCurve
import LTFP.MathlibExt.Calculus.GradientFlow
import LTFP.MathlibExt.Calculus.GradientFlowMovementBound
import LTFP.MathlibExt.Calculus.GradientFlowRandomInit
import LTFP.MathlibExt.Calculus.MultivariateHessianTaylor
import LTFP.MathlibExt.Calculus.ParameterMovementBoundedDeriv
import LTFP.MathlibExt.Calculus.TaylorRemainderBallRight
import LTFP.MathlibExt.Calculus.TaylorRemainderRightSided
import LTFP.MathlibExt.Probability.Adversary
import LTFP.MathlibExt.Probability.TotalVariation
import LTFP.MathlibExt.Probability.Distance.Bhattacharyya
import LTFP.MathlibExt.Probability.Distance.Pinsker
import LTFP.MathlibExt.Probability.Distributions.GaussianConjugatePosteriorSchur
import LTFP.MathlibExt.Probability.Distributions.GaussianObservationKernelMean
import LTFP.MathlibExt.Probability.Distributions.JointPriorObservationCrossCovariance
import LTFP.MathlibExt.Probability.Distributions.JointPriorObservationSndCovariance
import LTFP.MathlibExt.Probability.Distributions.JointPriorObservationSndMean
import LTFP.MathlibExt.Probability.Distributions.MultivariateGaussian
import LTFP.MathlibExt.Probability.Distributions.MultivariateGaussianNoiseCovariance
import LTFP.MathlibExt.Probability.Distributions.RegressionCLMCovariance
import LTFP.MathlibExt.Probability.DonskerVaradhan
import LTFP.MathlibExt.Probability.FunctionClassConcentration
import LTFP.MathlibExt.Probability.KullbackLeibler
import LTFP.MathlibExt.Probability.Moments.SubExponential
import LTFP.MathlibExt.Probability.LeCam
import LTFP.MathlibExt.Probability.LinearClassClosedBallCover
import LTFP.MathlibExt.Probability.LinearClassCoveringFinite
import LTFP.MathlibExt.Probability.LinearClassSampleCover
import LTFP.MathlibExt.Probability.LinearClassSampleCoverCard
import LTFP.MathlibExt.Probability.LinearizedRiskLipschitz
import LTFP.MathlibExt.Probability.LinearizedRiskSampleCover
import LTFP.MathlibExt.Probability.CoveringNumberEuclidean
import LTFP.MathlibExt.Probability.CoveringNumberReal
import LTFP.MathlibExt.Probability.Symmetrization
import LTFP.MathlibExt.Probability.WideNetworkDudley
import LTFP.MathlibExt.MatrixAnalysis.CStarMatrixInvAntiOnPos
import LTFP.MathlibExt.MatrixAnalysis.CStarOperatorMonotone
import LTFP.MathlibExt.MatrixAnalysis.InvAntiOnPos
import LTFP.MathlibExt.MatrixAnalysis.Lieb
import LTFP.MathlibExt.MatrixAnalysis.OperatorAntitoneScalarBridge
import LTFP.MathlibExt.MatrixAnalysis.OperatorConcaveScalarBridge
import LTFP.MathlibExt.MatrixAnalysis.OperatorConvexScalarBridge
import LTFP.MathlibExt.MatrixAnalysis.OperatorMonotoneScalarBridge
import LTFP.MathlibExt.Topology.UAT
